version: '3.4'

services:
  cinemaxum.movie.api:
    image: ${DOCKER_REGISTRY-}cinemaxummovieapi
    build:
      context: .
      dockerfile: Services/Movie/Cinemaxum.Movie.Api/Dockerfile

  cinemaxum.catalog.api:
    image: ${DOCKER_REGISTRY-}cinemaxumcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Cinemaxum.Catalog.Api/Dockerfile